import type {
  Category,
  Neighborhood,
  Order,
  Product,
  Shop,
  User,
} from "./types";

export const neighborhoods: Neighborhood[] = [
  {
    id: "cp",
    name: "Connaught Place",
    area: "New Delhi",
    coordinates: { lat: 28.6328, lng: 77.2197 },
  },
  {
    id: "karol",
    name: "Karol Bagh",
    area: "Central Delhi",
    coordinates: { lat: 28.6518, lng: 77.1905 },
  },
  {
    id: "saket",
    name: "Saket",
    area: "South Delhi",
    coordinates: { lat: 28.5244, lng: 77.2066 },
  },
  {
    id: "noida",
    name: "Sector 18",
    area: "Noida",
    coordinates: { lat: 28.5708, lng: 77.326 },
  },
];

export const users: User[] = [
  {
    id: "u-buyer",
    name: "Priya Sharma",
    email: "priya@example.com",
    role: "buyer",
  },
  {
    id: "u-gupta",
    name: "Ramesh Gupta",
    email: "gupta@dukkan.shop",
    role: "seller",
    shopId: "shop-gupta",
  },
  {
    id: "u-fresh",
    name: "Ananya Fresh",
    email: "ananya@freshdaily.shop",
    role: "seller",
    shopId: "shop-fresh",
  },
  {
    id: "u-steel",
    name: "Vikram Metals",
    email: "vikram@metals.shop",
    role: "seller",
    shopId: "shop-steel",
  },
  {
    id: "u-admin",
    name: "Dukkan Ops",
    email: "ops@dukkan.in",
    role: "admin",
  },
];

export const categories: Category[] = [
  { id: "grocery", name: "Grocery", emoji: "🛒" },
  { id: "fresh", name: "Fruits & veg", emoji: "🥬" },
  { id: "dairy", name: "Dairy", emoji: "🥛" },
  { id: "snacks", name: "Snacks", emoji: "🍪" },
  { id: "home", name: "Home", emoji: "🏠" },
  { id: "electronics", name: "Electronics", emoji: "🔌" },
  { id: "industrial", name: "Industrial", emoji: "⚙️" },
  { id: "apparel", name: "Apparel", emoji: "👕" },
];

export const shops: Shop[] = [
  {
    id: "shop-gupta",
    name: "Gupta Kirana & General",
    ownerUserId: "u-gupta",
    category: "grocery",
    description:
      "Neighbourhood kirana with daily staples, packaged foods, and household essentials. Same-lane pickup or partner drop.",
    address: "14, Inner Circle, Connaught Place, New Delhi",
    coordinates: { lat: 28.631, lng: 77.217 },
    rating: 4.6,
    reviews: 1284,
    verified: true,
    gstin: "07AABCG1234R1Z5",
    yearStarted: 1998,
    deliveryModes: ["partner", "shop"],
    status: "active",
  },
  {
    id: "shop-fresh",
    name: "FreshDaily Mandi",
    ownerUserId: "u-fresh",
    category: "fresh",
    description:
      "Morning-picked fruits and vegetables. Shop riders for nearby societies; Dukkan partner for the rest of the radius.",
    address: "B-22, Karol Bagh Main Bazaar, New Delhi",
    coordinates: { lat: 28.6502, lng: 77.1928 },
    rating: 4.8,
    reviews: 902,
    verified: true,
    gstin: "07AABCF5678R1Z2",
    yearStarted: 2016,
    deliveryModes: ["partner", "shop"],
    status: "active",
  },
  {
    id: "shop-milk",
    name: "Mother Dairy Booth 41",
    ownerUserId: "u-gupta",
    category: "dairy",
    description: "Milk, curd, paneer and ice cream from a local booth.",
    address: "Janpath Lane, New Delhi",
    coordinates: { lat: 28.6255, lng: 77.2188 },
    rating: 4.4,
    reviews: 410,
    verified: true,
    yearStarted: 2009,
    deliveryModes: ["partner"],
    status: "active",
  },
  {
    id: "shop-steel",
    name: "Vikram Industrial Metals",
    ownerUserId: "u-steel",
    category: "industrial",
    description:
      "IndiaMART-style wholesale for fasteners, sheets, and hardware. MOQ friendly for workshops.",
    address: "Okhla Phase II, New Delhi",
    coordinates: { lat: 28.5355, lng: 77.273 },
    rating: 4.3,
    reviews: 188,
    verified: true,
    gstin: "07AABCV9012R1Z8",
    yearStarted: 2004,
    deliveryModes: ["shop"],
    status: "active",
  },
  {
    id: "shop-noida",
    name: "QuickMart Noida 18",
    ownerUserId: "u-fresh",
    category: "grocery",
    description: "Hyperlocal grocery for Sector 18 — outside typical CP radius.",
    address: "Atta Market, Sector 18, Noida",
    coordinates: { lat: 28.5705, lng: 77.3215 },
    rating: 4.5,
    reviews: 640,
    verified: true,
    yearStarted: 2021,
    deliveryModes: ["partner", "shop"],
    status: "active",
  },
  {
    id: "shop-pending",
    name: "Kailash Electronics",
    ownerUserId: "u-steel",
    category: "electronics",
    description: "Chargers, cables, and small appliances. Awaiting admin approval.",
    address: "Lajpat Nagar, New Delhi",
    coordinates: { lat: 28.569, lng: 77.243 },
    rating: 0,
    reviews: 0,
    verified: false,
    yearStarted: 2024,
    deliveryModes: ["partner", "shop"],
    status: "pending",
  },
];

export const products: Product[] = [
  {
    id: "p-atta",
    shopId: "shop-gupta",
    name: "Aashirvaad Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "grocery",
    description: "Stone-ground style chakki atta for rotis. 5 kg pack.",
    price: 268,
    mrp: 310,
    unit: "5 kg",
    stock: 42,
    rating: 4.5,
    reviews: 2104,
    imageLabel: "Atta",
    imageHue: 32,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-rice",
    shopId: "shop-gupta",
    name: "India Gate Basmati Rice",
    brand: "India Gate",
    category: "grocery",
    description: "Aged basmati, everyday cooking pack.",
    price: 189,
    mrp: 225,
    unit: "1 kg",
    stock: 60,
    rating: 4.4,
    reviews: 980,
    imageLabel: "Rice",
    imageHue: 48,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-oil",
    shopId: "shop-gupta",
    name: "Fortune Sunlite Refined Oil",
    brand: "Fortune",
    category: "grocery",
    description: "Refined sunflower oil pouch.",
    price: 145,
    mrp: 165,
    unit: "1 L",
    stock: 28,
    rating: 4.3,
    reviews: 540,
    imageLabel: "Oil",
    imageHue: 50,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-detergent",
    shopId: "shop-gupta",
    name: "Surf Excel Easy Wash",
    brand: "Surf Excel",
    category: "home",
    description: "Detergent powder for daily wash.",
    price: 118,
    mrp: 135,
    unit: "1 kg",
    stock: 35,
    rating: 4.6,
    reviews: 770,
    imageLabel: "Wash",
    imageHue: 210,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner"],
  },
  {
    id: "p-tomato",
    shopId: "shop-fresh",
    name: "Farm Tomatoes",
    brand: "FreshDaily",
    category: "fresh",
    description: "Local mandi tomatoes, rinsed and packed.",
    price: 42,
    mrp: 55,
    unit: "500 g",
    stock: 80,
    rating: 4.7,
    reviews: 320,
    imageLabel: "Tomato",
    imageHue: 8,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-banana",
    shopId: "shop-fresh",
    name: "Robusta Bananas",
    brand: "FreshDaily",
    category: "fresh",
    description: "Ripe bunch, ready to eat.",
    price: 49,
    mrp: 60,
    unit: "6 pcs",
    stock: 40,
    rating: 4.5,
    reviews: 190,
    imageLabel: "Banana",
    imageHue: 52,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-spinach",
    shopId: "shop-fresh",
    name: "Palak Bunch",
    brand: "FreshDaily",
    category: "fresh",
    description: "Leafy spinach, trimmed.",
    price: 25,
    mrp: 30,
    unit: "1 bunch",
    stock: 55,
    rating: 4.6,
    reviews: 88,
    imageLabel: "Palak",
    imageHue: 128,
    moq: 1,
    status: "approved",
    deliveryModes: ["shop"],
  },
  {
    id: "p-milk",
    shopId: "shop-milk",
    name: "Toned Milk",
    brand: "Mother Dairy",
    category: "dairy",
    description: "Chilled pouch milk.",
    price: 30,
    mrp: 32,
    unit: "500 ml",
    stock: 120,
    rating: 4.8,
    reviews: 1500,
    imageLabel: "Milk",
    imageHue: 200,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner"],
  },
  {
    id: "p-paneer",
    shopId: "shop-milk",
    name: "Malai Paneer",
    brand: "Mother Dairy",
    category: "dairy",
    description: "Fresh paneer block.",
    price: 95,
    mrp: 110,
    unit: "200 g",
    stock: 22,
    rating: 4.5,
    reviews: 410,
    imageLabel: "Paneer",
    imageHue: 40,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner"],
  },
  {
    id: "p-chips",
    shopId: "shop-gupta",
    name: "Lays Magic Masala",
    brand: "Lays",
    category: "snacks",
    description: "Crispy potato chips.",
    price: 20,
    mrp: 20,
    unit: "52 g",
    stock: 90,
    rating: 4.4,
    reviews: 3000,
    imageLabel: "Chips",
    imageHue: 18,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-bolt",
    shopId: "shop-steel",
    name: "SS 304 Hex Bolts M8",
    brand: "Vikram Metals",
    category: "industrial",
    description: "Stainless fasteners, box of 100. Shop dispatch only.",
    price: 420,
    mrp: 480,
    unit: "100 pcs",
    stock: 200,
    rating: 4.2,
    reviews: 64,
    imageLabel: "Bolts",
    imageHue: 220,
    moq: 2,
    status: "approved",
    deliveryModes: ["shop"],
  },
  {
    id: "p-sheet",
    shopId: "shop-steel",
    name: "GI Sheet 24 Gauge",
    brand: "Vikram Metals",
    category: "industrial",
    description: "Galvanised sheet for fabrication. Pickup or shop tempo.",
    price: 1850,
    mrp: 2100,
    unit: "8x4 ft",
    stock: 18,
    rating: 4.1,
    reviews: 27,
    imageLabel: "Sheet",
    imageHue: 230,
    moq: 1,
    status: "approved",
    deliveryModes: ["shop"],
  },
  {
    id: "p-noida-atta",
    shopId: "shop-noida",
    name: "Patanjali Atta",
    brand: "Patanjali",
    category: "grocery",
    description: "Only listed when buyer location is near Noida.",
    price: 245,
    mrp: 280,
    unit: "5 kg",
    stock: 30,
    rating: 4.3,
    reviews: 120,
    imageLabel: "Atta",
    imageHue: 28,
    moq: 1,
    status: "approved",
    deliveryModes: ["partner", "shop"],
  },
  {
    id: "p-pending-charger",
    shopId: "shop-pending",
    name: "65W GaN Charger",
    brand: "Kailash",
    category: "electronics",
    description: "Awaiting catalogue approval.",
    price: 1299,
    mrp: 1999,
    unit: "1 pc",
    stock: 12,
    rating: 0,
    reviews: 0,
    imageLabel: "USB",
    imageHue: 260,
    moq: 1,
    status: "pending",
    deliveryModes: ["partner", "shop"],
  },
];

export const seedOrders: Order[] = [
  {
    id: "ORD-1042",
    buyerId: "u-buyer",
    shopId: "shop-gupta",
    items: [
      { productId: "p-atta", quantity: 1, deliveryMode: "partner" },
      { productId: "p-milk", quantity: 2, deliveryMode: "partner" },
    ],
    deliveryMode: "partner",
    status: "out_for_delivery",
    total: 328,
    createdAt: "2026-08-23T09:12:00.000Z",
    address: "Flat 12B, Janpath Residency, Connaught Place",
  },
];
